### ISSUE TITLE
Ch8 question: LSP for `AddBookmarkCommand.execute`

### ISSUE THREAD

**Issue by jpy-git** [daneah/practices-of-the-python-pro#8]
In chapter 8 we introduce the [`Command`](https://github.com/daneah/practices-of-the-python-pro/blob/98bd0a1273d3a3d75f20069cc38d112ea09e6cec/ch08/commands.py#L12-L15) abstract base class and add `data=None` args to some of the `execute` methods (e.g. [`CreateBookmarksTableCommand.execute`](https://github.com/daneah/practices-of-the-python-pro/blob/98bd0a1273d3a3d75f20069cc38d112ea09e6cec/ch08/commands.py#L19)) to satisfy LSP.

However, `AddBookmarkCommand.execute` still has an additional `timestamp` arg.
https://github.com/daneah/practices-of-the-python-pro/blob/98bd0a1273d3a3d75f20069cc38d112ea09e6cec/ch08/commands.py#L29-L33

Should `timestamp` also be passed in as part of the `data` dict to keep the method signature consistent with the base?
```python
class AddBookmarkCommand(Command):
    def execute(self, data):
        data["date_added"] = data.get("date_added") or datetime.utcnow().isoformat()
        db.add("bookmarks", data)
        return "Bookmark added!"
```
Thanks!

**Comment by daneah** [comment]
Hey @jpy-git, great question! My understanding of LSP is that substituting an instance of a class with an instance of one of its subclasses meets the LSP so long as the subclass instance doesn't break the code. Because the `Command` base has the `data` argument, all its subclasses must too. On the other hand, because the `AddBookmarkCommand` initializer adds an optional argument, replacing a `Command` instance (which you can't _really_ have because it's abstract, but I digress) with an `AddBookmarkCommand` instance will continue to work, and continue to meet LSP.

That all being said, passing the timestamp in as part of the `data` argument would certainly be viable and keep the signatures more consistent, which can still be valuable—LSP aside. I'd need to go back when I have some more time to see why I chose to add the timestamp as an additional argument!

**Comment by jpy-git** [comment]
@daneah Makes sense thanks! Just finished the book 😄
